### ISSUE TITLE
No provided tag for v1.15.3

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-localization#19]
This commit: https://github.com/FusionAuth/fusionauth-localization/commit/f56610667f10d71c4c13f292cd419ba7a352eb63

Is not tagged. Automated installation scripts are failing trying to download the right version.

**Comment by robotdan** [comment]
These files are managed by our versioning process, 1.15.3 is not released yet, there will not be a tag for it yet.

**Comment by soullivaneuh** [comment]
Doh, I didn't read the "Pending Release" state from your website, sorry about that.
