### ISSUE TITLE
Spanish localization

### ISSUE THREAD

**Issue by lluisgener** [FusionAuth/fusionauth-localization#25]
I've been working in localization to spanish.

Find it attached.
[fauth_es.txt](https://github.com/FusionAuth/fusionauth-localization/files/4402056/fauth_es.txt)

**Comment by robotdan** [comment]
Thanks @lluisgener I appreciate your contribution! 

Can you submit this using a pull request? There are instructions in the README.

**Comment by robotdan** [comment]
Copied in via commit https://github.com/FusionAuth/fusionauth-localization/commit/b9b1c4affa6f47d25c8aa81be89b5f9964cb5445
